// Fixed, unmistakably-test identifiers. Fixed (not randomised per run) so
// the collision guard in guard.ts can check for them by name before
// touching anything, and so a failed run leaves an unambiguous trace
// instead of an orphaned org named "Test Org 4f8a2b".

export const ORG_A_SLUG = 'rls-test-org-a';
export const ORG_B_SLUG = 'rls-test-org-b';
export const ORG_A_NAME = '__RLS_TEST_ORG_A__ (auto-generated by tests/rls, safe to delete)';
export const ORG_B_NAME = '__RLS_TEST_ORG_B__ (auto-generated by tests/rls, safe to delete)';

// RFC 2606 reserved TLD — guaranteed never to be a real deliverable
// address, so a fixture email can never collide with a real user's.
export const EMAIL_DOMAIN = 'rls-tests.invalid';
